### ISSUE TITLE
Purpose of this package

### ISSUE THREAD

**Issue by ToucheSir** [JuliaDebug/CassetteOverlay.jl#7]
I saw this in my GH feed and was hooked in by "cassette" + "overlay" :). Is/will there be some writeup about what this library is good for, how it compares to https://github.com/JuliaCompilerPlugins/Mixtape.jl and the original Cassette, etc?

**Comment by Keno** [comment]
It's just a small package that uses the cassette mechanism to provide overlay table support. Overlay tables can be used directly by abstract interpreters, but tend to have a bad debugging experience, because the absint interface isn't particularly stable, so we don't have any debug tooling for it. This helps a bit.
